######
#
# A simple Makefile
#
######

all::
all:: syllabus

######

syllabus: ; \
pdflatex syllabus.tex

######

clean:: ; rm -f *~
clean:: ; rm -f syllabus.aux
clean:: ; rm -f syllabus.log

######

cleanall:: clean

###### end of [Makefile] ######
