######
MYATSCC=myatscc
######
all::
all:: \
lecture-09-14_dats
######
lecture-09-14_dats: \
lecture-09-14.dats; \
$(MYATSCC) lecture-09-14.dats
######
clean:: ; rm -f *~
######
cleanall:: clean
cleanall:: ; rm -f lecture-09-14_dats
######

###### end of [Makefile] ######
